#################################################################
#   Documentation on the wiki
#   http://cqr-wiki.org/index.php?title=Loot_Configuration
#
#   Identifier = Item, Meta, MinCount, MaxCount, Chance, [Enchant, MinLevel, MaxLevel, [Treasure, [EnchantChance]]]
#################################################################
iron = minecraft:iron_ingot,0,3,6,60
gold = minecraft:gold_ingot,0,3,6,40
diamond = minecraft:diamond,0,1,3,10
coal = minecraft:coal,0,4,8,70
flint = minecraft:flint,0,3,6,60
redstone = minecraft:redstone,0,5,15,50
sticks = minecraft:stick,0,2,4,40
emerald = minecraft:emerald,0,2,6,20


#Modded Loot, alphabatized by mod name.

#AfraidOfTheDark
GnomeMetal = afraidofthedark:gnomish_metal_ingot,0,37,64,7
SleepypotionAOTD = afraidofthedark:sleeping_potion,0,1,1,4

#ancientwarfare
steelingotancientwarfare = ancientwarfare:steel_ingot,0,3,6,21

#aquaculture
driftwood = aquaculture:loot,0,2,6,40
box = aquaculture:loot,4,2,7,30
lockbox = aquaculture:loot,5,1,3,10

#astralsorcery
aquamarine = astralsorcery:itemcraftingcomponent,0,8,15,39

#betterwithmods
bwmsoap = betterwithmods:material,50,1,6,21
bwmhellfire = betterwithmods:material,17,2,4,8
bwmtallow = betterwithmods:material,13,3,7,39

#bloodmagic
slate = bloodmagic:slate,0,5,12,60

#botania
youmustconstructadditionalpylons = botania:pylon,0,2,2,1
abstruseplatform = botania:platform,1,1,4,6
runebase = botania:rune,0,1,7,42
runebase2 = botania:rune,1,1,7,42
runebase3 = botania:rune,2,1,7,42
runebase4 = botania:rune,3,1,7,42
runeseason1 = botania:rune,5,1,7,17
runeseason2 = botania:rune,4,1,7,17
runeseason3 = botania:rune,6,1,7,17
runeseason1againtheactorshavetobepaidmoreifwecallitseason4 = botania:rune,7,1,7,17
runemana = botania:rune,8,1,7,13
expensivemagicard = botania:blacklotus,0,3,11,29
blackerlotus = botania:blacklotus,1,1,3,7
manapearl = botania:manaresource,1,1,2,2
manadiamond = botania:manaresource,2,1,2,2
manadust = botania:manaresource,23,12,27,39
manastring = botania:manaresource,16,4,11,31
manasteel = botania:manaresource,0,3,9,55
smallrewardbagexbo = extrabotany:rewardbag,0,2,7,35
medrewardbackexbo = extrabotany:rewardbag,1,1,1,14

#botanicadditions
manalapis = botanicadds:mana_lapis,0,2,11,13

#bountifulbaubles
bbmagicmirror = bountifulbaubles:magicmirror,0,1,1,15
bbballoon = bountifulbaubles:trinketballoon,0,1,1,12
bbsunglass = bountifulbaubles:trinketmagiclenses,0,1,1,11
bbflywheel = bountifulbaubles:ringflywheel,0,1,1,8
bbflaregun = bountifulbaubles:flaregun,0,1,1,22

#charcoalpit
cokecoal1 = charcoal_pit:item_coke,0,3,7,35
alchcoal1 = charcoal_pit:alchemical_coal,0,1,1,2

#deeperdepths
copperingotdd = deeperdepths:material,0,8,48,50
amysharddd = deeperdepths:material,1,3,15,30

#dungeontactics
dtsilveringot = dungeontactics:silver_ingot,0,5,9,20
dtsteelingot = dungeontactics:steel_ingot,0,1,2,31
dtmithrilingot = dungeontactics:mithril_ingot,0,1,1,8
dtironchainlinks = dungeontactics:ironlinks,0,9,18,22

#Elementaristics
ELEMEN_ArcaneGem = elementaristics:gem_arcane,0,2,5,14

#enderio
eiosiggrindingball = enderio:item_material,57,1,1,45
eioesball = enderio:item_alloy_ball,8,1,1,5
eiolumigrindball = enderio:item_material,59,1,1,35
eioendergrindball = enderio:item_material,58,1,1,35
eioweathercrys = enderio:item_material,18,1,1,7
eioendermanhead = enderio:block_enderman_skull,0,1,1,7
eiomachinechassis = enderio:item_material,1,1,1,24

eiosilicon = enderio:item_material,5,5,35,32
pulsatingironingot = enderio:item_alloy_ingot,5,2,4,14
redstonealloyingot = enderio:item_alloy_ingot,3,12,24,32
conductiveironingot = enderio:item_alloy_ingot,4,3,20,8
eioironalloy = enderio:item_alloy_ingot,9,9,18,30
eioelectricalsteel = enderio:item_alloy_ingot,0,2,4,5
eioenergeticingot = enderio:item_alloy_ingot,1,1,3,4
eiosoulariumingot = enderio:item_alloy_ingot,7,3,6,18
conduitbindereio = enderio:item_material,4,25,32,6
eioendermensummoningpowder = enderio:block_infinity_fog,0,1,7,8
eiopulsatingcrystal = enderio:item_material,14,1,1,4
eiovibegear = enderio:item_material,13,2,4,1
eioenergygear = enderio:item_material,12,2,4,2
eiodarkgear = enderio:item_material,73,2,4,11
eioirongear = enderio:item_material,11,2,4,18

#ExtraUtils
euenchanted = extrautils2:ingredients,12,3,7,15
eusuncrys = extrautils2:suncrystal,0,1,1,21

#futuremc
honeycomb = futuremc:honeycomb,0,7,18,28

#GrimoireOfGaia
gogwritingquil = grimoireofgaia:misc_quill,0,2,7,33
gogfur = grimoireofgaia:misc_fur,0,4,20,60
gogstonecoal = grimoireofgaia:misc_furnace_fuel,0,3,25,14
gogfirerock = grimoireofgaia:misc_soul_fiery,0,3,9,20
gogdiamondbox = grimoireofgaia:box_diamond,0,1,1,2
goggoldbox = grimoireofgaia:box_gold,0,1,1,18
gogironbox = grimoireofgaia:box_iron,0,1,1,32

#immersiveengineering
graphiteingot = immersiveengineering:material,19,2,4,19
iecopper = immersiveengineering:metal,0,4,8,42
iealuminum = immersiveengineering:metal,1,3,5,61
ielead = immersiveengineering:metal,2,3,6,47
iesilver = immersiveengineering:metal,3,3,6,53
ienickel = immersiveengineering:metal,4,3,6,52
ieuranium = immersiveengineering:metal,5,3,6,15
iecircuitboard = immersiveengineering:material,27,1,3,4

#IC2
ic2coppercable = ic2:cable,0,7,41,41
ic2coalcoke = ic2:coke,0,1,51,61
ic2rubber = ic2:crafting,0,2,29,79
ic2circuit = ic2:crafting,1,2,19,69
ic2advancedcircuit = ic2:crafting,2,1,2,6
ic2advancedalloy = ic2:crafting,3,1,2,4
ic2rawcarbonmesh = ic2:crafting,14,1,2,4
ic2compressedcoalball = ic2:crafting,17,2,8,23
ic2carbonplate = ic2:crafting,15,1,2,4
#cables don't work in this.
#ic2glassfibrecable = ic2:cable:1>.withTag({type: 1 as byte, insulation: 0 as byte})
#ic2tinsulatedcable = ic2:cable:4>.withTag({type: 4 as byte, insulation: 1 as byte})
#ic2tincable = ic2:cable:4>.withTag({type: 4 as byte, insulation: 0 as byte})
#ic2inscoppercable = ic2:cable>.withTag({type: 0 as byte, insulation: 1 as byte})
#ic23inshvcable = ic2:cable,3,.withTag({type: 3 as byte, insulation: 3 as byte})
#ic22insgoldcable = ic2:cable,2,
ic2machineblock = ic2:resource,13,1,2,29
ic2advancedmachineblock = ic2:resource,12,1,1,2
ic2credits = ic2:crafting,38,2,54,26
ic2mixedmetals = ic2:ingot,0,1,3,9
ic2bronze = ic2:ingot,1,3,6,60
ic2copper = ic2:ingot,2,3,6,70
ic2lead = ic2:ingot,3,3,6,40
ic2silver = ic2:ingot,4,3,6,40
ic2steel = ic2:ingot,5,3,6,33
ic2tin = ic2:ingot,6,3,6,70
ic2scrap = ic2:crafting,23,5,53,80
ic2scrapbox = ic2:crafting,24,1,4,20
ic2tincan = ic2:crafting,1,2,15,42
ic2fuelrod = ic2:crafting,9,3,15,11
ic2coil = ic2:crafting,5,2,8,31
ic2ironfurnace = ic2:te,46,1,2,42
ic2tinybattery = ic2:single_use_battery,0,6,59,22
ic2battery = ic2:re_battery,0,1,16,51
ic2hydratedcoaldust = ic2:dust,3,2,37,14
ic2rubbersapling = ic2:sapling,0,2,31,32
ic2scaffolding = ic2:scaffold,0,1,64,50
ic2MFSUupgradekit = ic2:upgrade_kit,0,1,1,15

#IndustrialForgoing
mfrplastic = industrialforegoing:plastic,0,15,28,40

#IndustrialRenewal
irfluidreader = industrialrenewal:fluid_gauge,0,2,5,5
irenergyreader = industrialrenewal:energy_level,0,2,5,5
irscaffold = industrialrenewal:scaffold,0,39,64,43
irfloor = industrialrenewal:industrial_floor,0,1,64,64
irspongeiron = industrialrenewal:sponge_iron,0,1,3,13
irironstick = industrialrenewal:stick_iron,0,5,19,40
irsteelstick = industrialrenewal:stick_steel,0,3,9,7
irsteelingot = industrialrenewal:ingot_steel,0,2,4,19
irrockslab = industrialrenewal:small_slab,0,29,47,40

#Just Dire Things
JDT_Coal4 = justdirethings:coal_t4,0,4,19,8
JDT_Coal1 = justdirethings:coal_t1,0,39,53,8
JDT_Coal2 = justdirethings:coal_t2,0,22,32,14
JDT_Coal3 = justdirethings:coal_t3,0,3,19,23
JDT_Metal = justdirethings:ferricore_ingot,0,2,4,50
JDT_Blazegem = justdirethings:blazegold_ingot,0,1,4,9

#LegendGear
InfusedStardustLG = legendgear:infused_stardust,0,5,19,28
LGStarPieceInfused = legendgear:infused_star_piece,0,2,5,11
LGStarstoneInfused = legendgear:infused_starstone,0,1,1,1
StarsteelLG = legendgear:starsteel_ingot,0,1,3,2
StarglassLG = legendgear:starglass_ingot,0,2,4,4

#Mekanism
mekosmium = mekanism:ingot,1,3,6,60
mekbronze = mekanism:ingot,2,3,6,30
mekcopper = mekanism:ingot,5,3,6,50
mektin = mekanism:ingot,6,3,6,50
mekglowstoneingot = mekanism:ingot,3,1,4,10
mekalloy1 = mekanism:enrichedalloy,0,2,8,40
mekalloy2 = mekanism:reinforcedalloy,1,1,2,5
mekcircuit1 = mekanism:controlcircuit,0,2,6,40
mekcircuit2 = mekanism:controlcircuit,1,2,4,9
mekdiamonddust = mekanism:otherdust,0,1,4,7
mekscrap = mekanism:scrap,0,8,29,60
mekflourite = mekanism:fluoriteclump,0,6,20,40
mekcakeuranium = mekanism:yellowcakeuranium,0,8,12,10
mekcarbonsquare = mekanism:compressedcarbon,0,1,4,50
mekredstonesquare = mekanism:compressedredstone,0,1,5,44
meksquarediamond = mekanism:compresseddiamond,0,1,2,4
mekplasticsheet = mekanism:hdpe_sheet,0,4,9,30
meksolar = mekanismgenerators:solarpanel,0,3,3,30
mekmuffling = mekanism:mufflingupgrade,0,4,4,39

#Mekanism CE Unofficial
#People using Mekanism CE have experienced crashes when attempting to generate loot that does not exist. Remove the "#" from the below lines to reenable CEU loot.
#meklead = mekanism:ingot,7,3,6,40
#mekuranium = mekanism:ingot,8,3,6,25

#minestrappolation5
redstonesnad = minestrapp:redstone_sandy,0,5,15,20
redstonefrost = minestrapp:redstone_frosted,0,5,15,20
redstonebrine = minestrapp:redstone_briny,0,5,15,20
redstoneice = minestrapp:redstone_icy,0,5,15,20
tiningotms = minestrapp:m_ingot,1,3,6,42
copperingotms = minestrapp:m_ingot,0,3,6,48

#MysticalWorld
SilverIngotMysticalWorld = mysticalworld:silver_ingot,0,2,6,32
AmethystGemMysticalWorld = mysticalworld:amethyst_gem,0,2,4,26
CopperIngotMysticalWorld = mysticalworld:copper_ingot,0,3,7,40

#ProdigyTech
ptferringot = prodigytech:ferramic_ingot,0,2,6,50
ptbigfuel = prodigytech:fuel_pellet_64,0,1,3,10
ptmidfuel = prodigytech:fuel_pellet_16,0,2,19,30
ptsmallfuel = prodigytech:fuel_pellet_4,0,18,63,40
ptinfernofuel = prodigytech:inferno_fuel,0,2,9,20
ptcarbonplate = prodigytech:carbon_plate,0,1,3,10
ptparticleboard = prodigytech:particle_board,0,14,57,15

#ProjectE
lowdustpe = projecte:item.pe_covalence_dust,0,2,40,14
middustpe = projecte:item.pe_covalence_dust,1,2,40,11
bigdustpe = projecte:item.pe_covalence_dust,2,2,40,7
pealchemicoal = projecte:item.pe_fuel,0,8,24,24
pemorbiusfuel = projecte:item.pe_fuel,1,4,12,15
aeternalisfuelpe = projecte:item.pe_fuel,2,1,2,2

#ProjectPlastic
plastigelpally = projectplastic:resource,7,11,29,42
plastibattery = projectplastic:resource,10,1,3,9

#RFTools
dimshardrft = rftools:dimensional_shard,0,2,6,11

#sakura
Sakusteel = sakura:materials,56,2,4,10

#superblocks
stickpackage = superblocks:pack_,37,2,3,10

#Tech Reborn
techreborn_ruby = techreborn:gem,0,1,3,37
techreborn_sapphire = techreborn:gem,1,1,3,37
techreborn_peridot = techreborn:gem,2,1,3,37
techreborn_garnet_r = techreborn:gem,3,1,3,29
techreborn_garnet_y = techreborn:gem,4,1,3,29
techreborn_steel = techreborn:ingot,12,1,5,8
techreborn_tin = techreborn:ingot,13,4,8,70
techreborn_zinc = techreborn:ingot,18,4,8,70
techreborn_refinediron = techreborn:ingot,19,3,6,60
techreborn_advancedalloy = techreborn:ingot,20,
techreborn_bronze = techreborn:ingot,2,3,6,59
techreborn_brass = techreborn:ingot,1,3,6,50
techreborn_aluminum = techreborn:ingot,0,4,8,70
techreborn_plutonium = techreborn:ingot,25,1,2,3
techreborn_uranium = techreborn:ingot,24,1,5,12
techreborn_thorium = techreborn:ingot,23,1,3,16
techreborn_mixedmetal = techreborn:ingot,21,1,2,11
techreborn_silver = techreborn:ingot,11,3,7,44
techreborn_nickel = techreborn:ingot,9,4,8,70
techreborn_lead = techreborn:ingot,8,4,8,70
techreborn_invar = techreborn:ingot,6,3,6,30
techreborn_electrum = techreborn:ingot,5,3,6,38
techreborn_copper = techreborn:ingot,4,4,8,70
techreborn_andradite = techreborn:dust,2,5,6,11
techreborn_almandine = techreborn:dust,0,5,6,11
techreborn_Cinnabar = techreborn:dust,11,5,21,7
techreborn_bauxite = techreborn:dust,5,4,8,70
techreborn_dark_ash = techreborn:dust,15,51,64,29
techreborn_magnesium = techreborn:dust,30,3,5,42
techreborn_galena = techreborn:dust,23,5,7,39
techreborn_basalt = techreborn:dust,4,8,48,50
techreborn_calcite = techreborn:dust,8,8,48,50
techreborn_marble = techreborn:dust,32,8,48,50
techreborn_pyrite = techreborn:dust,39,8,24,10
techreborn_saltpeter = techreborn:dust,44,8,16,50
techreborn_spalerite = techreborn:dust,50,4,5,8
techreborn_uvarovite = techreborn:dust,56,5,6,11
techreborn_insulatedcoppercable = techreborn:cable,5,16,48,60
techreborn_coppercable = techreborn:cable,0,16,48,20
techreborn_scrap = techreborn:part,33,3,24,40
techreborn_scrapbox = techreborn:scrapbox,0,1,1,4
techreborn_advanced_circuit_parts = techreborn:part,42,16,20,25
techreborn_rubber = techreborn:part,32,6,55,30
techreborn_sap = techreborn:part,31,22,55,10
techreborn_rubbersapling = techreborn:rubber_sapling,0,1,6,24
techreborn_10kwatercoolant = techreborn:part,36,1,9,40
techreborn_60heliumcoolant = techreborn:part,7,2,5,30
techreborn_180kheliumcoolant = techreborn:part,8,1,3,10
techreborn_ironfurnace = techreborn:iron_furnace,0,1,2,42
techreborn_biocell = techreborn:part,46,15,39,30
techreborn_machineframe = techreborn:machine_frame,0,1,2,59
techreborn_reinforcedglass = techreborn:reinforced_glass,0,2,4,10
techreborn_carbonfibre = techreborn:part,35,1,3,10

#TeslaCoreLib
tclspeed2 = teslacorelib:speed_tier2,0,2,8,10
tclenergy1 = teslacorelib:energy_tier1,0,2,8,30
tclenergy2 = teslacorelib:energy_tier2,0,2,8,10
tclspeed1 = teslacorelib:speed_tier1,0,2,8,30
tclmachineframe = teslacorelib:machine_case,0,1,4,35

#TouhouLittleMaidMob
TLMMPP = touhou_little_maid:power_point,0,2,7,60

#tconstruct
aluminumbrassingottconstruct = tconstruct:ingots,5,4,8,35
pigirontcon = tconstruct:ingots,4,1,5,15
knightslimetcon = tconstruct:ingots,3,1,1,3



#Witchery
witchery_hellhoundhead = witchery:hellhound_head,0,1,1,4
witchery_wolfhead = witchery:wolf_head,0,1,2,29
witchery_handofwitchery = witchery:witches_hand,0,1,1,12
witchery_purejar = witchery:purity_odor,0,3,16,12
witchery_milkjar = witchery:purified_milk,0,3,16,12
witchery_fouljar = witchery:foul_fume,0,3,16,12
witchery_hornedjar = witchery:horned_one_exhale,0,3,16,12
witchery_goddessjar = witchery:goddess_breath,0,3,16,12
witchery_rebirthjar = witchery:rebirth_hint,0,3,16,12
witchery_magicjar = witchery:magic_whiff,0,3,16,12
witchery_stinkyfortunejar = witchery:misfortune_reek,0,3,16,12
witchery_creepyheart = witchery:creeper_heart,0,1,1,14
witchery_lilsilver = witchery:silver_deposits,0,6,59,40
witchery_raisins = witchery:raising_brew,0,1,1,4
witchery_batpot = witchery:bats_brew,0,1,1,4
witchery_wastinbrew = witchery:wasting_brew,0,1,1,4
witchery_goldthread = witchery:golden_thread,0,2,6,14
witchery_quartzsphere = witchery:quartz_sphere,0,1,1,4
witchery_frogpiece = witchery:frogs_toe,0,5,9,14
witchery_owlbits = witchery:owlets_wing,0,4,12,14
witchery_doggytongue = witchery:dog_tongue,0,2,7,37
witchery_woolybat = witchery:bat_wool,0,8,23,42
witchery_spusty = witchery:spectral_dust,0,6,19,21
witchery_littlemutandis = witchery:mutandis,0,20,30,25
witchery_bigmutandis = witchery:mutandis_extremis,0,6,14,15
















