// Date: 05.10.2019 22:31:30
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.teamcqr.chocolatequestrepoured.client.models.entities.customarmor;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCQRGolemSmallArmor extends ModelBiped {

	public ModelCQRGolemSmallArmor(float scale) {
		super(scale);

		this.bipedRightLeg = new ModelRenderer(this, 0, 16);
		this.bipedRightLeg.addBox(-3F, 0F, -2F, 4, 12, 4, scale);
		this.bipedRightLeg.setRotationPoint(-2F, 12F, 0F);
		this.bipedRightLeg.setTextureSize(64, 32);
		this.bipedRightLeg.mirror = true;
		this.setRotation(this.bipedRightLeg, 0F, 0F, 0F);

		this.bipedLeftLeg = new ModelRenderer(this, 0, 16);
		this.bipedLeftLeg.addBox(-1F, 0F, -2F, 4, 12, 4, scale);
		this.bipedLeftLeg.setRotationPoint(2F, 12F, 0F);
		this.bipedLeftLeg.setTextureSize(64, 32);
		this.bipedLeftLeg.mirror = true;
		this.setRotation(this.bipedLeftLeg, 0F, 0F, 0F);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	@Override
	public void setRotationAngles(float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scaleFactor, Entity entityIn) {
		super.setRotationAngles(limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch, scaleFactor, entityIn);
	}

}
